alias glog='git log --oneline | head -n $1'
alias gb='git branch'
alias gcb='git checkout -b $1'
alias gc='git checkout $1'
alias gp='git push origin head'
alias gpr='git pull origin --rebase'
alias gcommit='git add . && git commit -m $1'